In [3]:
# Способ 1: Из строки (нужно закодировать)
text = "Hello"
b = text.encode('utf-8')  # b'Hello'
type(b)

bytes

In [5]:
# Способ 2: Напрямую через b'...'
b = b'Hello'
b

b'Hello'

In [6]:
# Способ 3: Из списка чисел
b = bytes([72, 101, 108, 108, 111])  # b'Hello'
b

b'Hello'

In [8]:
# Способ 4: Пустой bytes
b = b''
b

b''

In [9]:
text = "Привет"
b = text.encode('utf-8')

print(b)                # b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82'
print(b[0])             # 208 (первый байт)
print(b.hex())          # d09f... (шестнадцатеричное представление)

b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82'
208
d09fd180d0b8d0b2d0b5d182

In [11]:
ba = bytearray(b'Hello')
ba[0] = 71  # всё ещё 'H', т.к. 72 — это код 'H'
ba[1] = 101 # 'e'
print(ba)   # bytearray(b'Hello')

bytearray(b'Gello')

In [12]:
str(ba)

"bytearray(b'Gello')"

In [13]:
def greet(name: str):
    return f"Hello, {name}"

b = b"Alice"
greet(b)  # TypeError: expected str, got bytes

"Hello, b'Alice'"

In [19]:
def sum_of_two(arr:list, target:int):
    set_nums = set()
    result = []
    for num in arr:
        if (target - num) in set_nums:
            result.append((target-num,num))
        else:
            set_nums.add(num)
    
    return result

In [20]:
arr = [1,3,5,8,10]
target = 13
sum_of_two(arr,target)

[(5, 8), (3, 10)]

In [21]:
arr = [2, 3, 4, 3]
target = 6
sum_of_two(arr,target)
# Ожидаемый результат: [(2,4), (3,3)]
# Твой код выдаст: [(2,4), (3,3), (3,3)] (повтор)

[(2, 4), (3, 3)]

In [22]:
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# Строим матрицу связей
linkage_matrix = linkage(X, method='ward')

# Рисуем дендрограмму
plt.figure(figsize=(12, 6))
dendrogram(linkage_matrix, truncate_mode='level', p=5)
plt.xlabel('Индексы объектов')
plt.ylabel('Расстояние')
plt.title('Дендрограмма (Ward)')
plt.show()

NameError: name 'X' is not defined

In [24]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

print(dir(LinearRegression()))
# ['__class__', '__delattr__', ... , 'coef_', 'fit', 'get_params', 'intercept_', 'predict', 'score', ...]

['__abstractmethods__', '__annotate_func__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_decision_function', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_class_level_metadata_request_values', '_get_doc_link', '_get_fitted_attr_html', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_set_intercept', '_validate_params', 'copy_X', 'fit', 'fit_intercept', 'get_metadata_routing', 'get_params', 'n_jobs', 'positive', 'predict', 'score', 'set_fit_request', 'set_params', 'set_score_request', 'tol']

In [25]:
class MyClass:
    def __init__(self):
        self.x = 10
        self.y = 20

obj = MyClass()
print(dir(obj))     # ['__class__', ..., 'x', 'y']
print(vars(obj))    # {'x': 10, 'y': 20}
print(obj.__dict__) # {'x': 10, 'y': 20}

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', 'x', 'y']
{'x': 10, 'y': 20}
{'x': 10, 'y': 20}

In [28]:
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6]
})

# Сумма по столбцам (axis=0 — по умолчанию)
print(df.apply(sum, axis=0))
# a     6
# b    15
# dtype: int64

# Сумма по строкам (axis=1)
print()
# 0    5
# 1    7
# 2    9
# dtype: int64

a     6
b    15
dtype: int64

In [29]:
df.apply(sum, axis=1)

0    5
1    7
2    9
dtype: int64

In [27]:
df

   a  b
0  1  4
1  2  5
2  3  6

In [30]:
def category(row):
    if row['a'] > 2:
        return 'high'
    return 'low'

df['cat'] = df.apply(category, axis=1)
df
#    a  b   cat
# 0  1  4   low
# 1  2  5   low
# 2  3  6  high

   a  b   cat
0  1  4   low
1  2  5   low
2  3  6  high

In [32]:
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6]
})

# Старый способ (удалён)
# df.applymap(lambda x: x ** 2)   

# Новый способ (работает)
df.map(lambda x: x ** 2)   

# Результат:
#     a   b
# 0   1  16
# 1   4  25
# 2   9  36

   a   b
0  1  16
1  4  25
2  9  36

In [33]:
try:
    x = int("abc")  # ValueError
except ValueError as e:
    print(f"Ошибка: {e}")

Ошибка: invalid literal for int() with base 10: 'abc'

In [34]:
try:
    x = 1 / 0
except Exception as e:
    print(f"Что-то пошло не так: {e}")

Что-то пошло не так: division by zero

In [35]:
# List — можно изменить
lst = [1, 2, 3]
lst[0] = 10   # OK
lst.append(4) # OK

# Tuple — нельзя изменить
tpl = (1, 2, 3)
tpl[0] = 10   # ❌ TypeError: 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

In [36]:
# tuple — можно (хешируемый)
d = {(1, 2): "point"}
print(d[(1, 2)])  # ✅

# list — нельзя (не хешируемый)
d = {[1, 2]: "point"}  # ❌ TypeError: unhashable type: 'list'

point

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [37]:
tpl = (5)    # Это int, а не tuple!
print(type(tpl))  # <class 'int'>

tpl = (5,)   # Это tuple
print(type(tpl))  # <class 'tuple'>

<class 'int'>
<class 'tuple'>

In [38]:
tpl = ([1, 2], 3)
tpl[0].append(3)  # ✅ OK
print(tpl)  # ([1, 2, 3], 3)

tpl[1] = 10  # ❌ TypeError (кортеж в целом неизменяем)

([1, 2, 3], 3)

TypeError: 'tuple' object does not support item assignment

In [39]:
def squares(n):
    result = []
    for i in range(n):
        result.append(i ** 2)
    return result

print(squares(5))  # [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]

In [40]:
def squares_gen(n):
    for i in range(n):
        yield i ** 2

In [41]:
gen = squares_gen(5)
print(gen)  # <generator object squares_gen at 0x...>

<generator object squares_gen at 0x000002A53536E330>

In [42]:
for val in gen:
    print(val)  # 0, 1, 4, 9, 16 (по одному)

0
1
4
9
16

In [43]:
def infinite_count():
    i = 0
    while True:
        yield i
        i += 1

counter = infinite_count()
print(next(counter))  # 0
print(next(counter))  # 1
print(next(counter))  # 2
# ... можно продолжать бесконечно

0
1
2

In [46]:
next(counter)

5

In [48]:
import pandas as pd

df = pd.DataFrame({
    'a': [10, 20, 30, 40, 50],
    'b': [100, 200, 300, 400, 500]
}, index=[2, 5, 7, 10, 12])

df
#     a    b
# 2  10  100
# 5  20  200
# 7  30  300
# 10 40  400
# 12 50  500

     a    b
2   10  100
5   20  200
7   30  300
10  40  400
12  50  500

In [50]:
df.loc[5]

a     20
b    200
Name: 5, dtype: int64

In [51]:
df.loc[5:10]

     a    b
5   20  200
7   30  300
10  40  400

In [53]:
df.loc[5:10, 'a']

5     20
7     30
10    40
Name: a, dtype: int64

In [54]:
df.loc[df['a'] > 20]

     a    b
7   30  300
10  40  400
12  50  500

In [55]:
df.iloc[1]

a     20
b    200
Name: 5, dtype: int64

In [56]:
df.iloc[1:4]

     a    b
5   20  200
7   30  300
10  40  400

In [57]:
df.iloc[1:4, 0]

5     20
7     30
10    40
Name: a, dtype: int64

In [58]:
df.iloc[(df['a'] > 20).values]

     a    b
7   30  300
10  40  400
12  50  500

In [59]:
import pandas as pd

df = pd.DataFrame({
    'group': ['A', 'A', 'B', 'B', 'B'],
    'value': [10, 20, 30, 40, 50]
})

# agg — одна строка на группу
agg_result = df.groupby('group')['value'].mean()
print(agg_result)
# group
# A    15.0
# B    40.0
# Name: value, dtype: float64

print(len(agg_result))  # 2

group
A    15.0
B    40.0
Name: value, dtype: float64
2

In [66]:
df.groupby('group')['value'].transform('mean')

0    15.0
1    15.0
2    40.0
3    40.0
4    40.0
Name: value, dtype: float64

In [67]:
# transform — та же длина, что и исходный df
transform_result = df.groupby('group')['value'].transform('mean')
print(transform_result)
# 0    15.0
# 1    15.0
# 2    40.0
# 3    40.0
# 4    40.0
# Name: value, dtype: float64

print(len(transform_result))  # 5 (как исходный df)

0    15.0
1    15.0
2    40.0
3    40.0
4    40.0
Name: value, dtype: float64
5

In [68]:
df['group_mean'] = df.groupby('group')['value'].transform('mean')
print(df)
#   group  value  group_mean
# 0     A     10        15.0
# 1     A     20        15.0
# 2     B     30        40.0
# 3     B     40        40.0
# 4     B     50        40.0

  group  value  group_mean
0     A     10        15.0
1     A     20        15.0
2     B     30        40.0
3     B     40        40.0
4     B     50        40.0

In [69]:
df['deviation'] = df['value'] - df.groupby('group')['value'].transform('mean')
print(df)
#   group  value  group_mean  deviation
# 0     A     10        15.0       -5.0
# 1     A     20        15.0        5.0
# 2     B     30        40.0      -10.0
# 3     B     40        40.0        0.0
# 4     B     50        40.0       10.0

  group  value  group_mean  deviation
0     A     10        15.0       -5.0
1     A     20        15.0        5.0
2     B     30        40.0      -10.0
3     B     40        40.0        0.0
4     B     50        40.0       10.0

In [70]:

df = pd.DataFrame({
    'date': ['2024-01-01', '2024-01-02', '2024-01-03'],
    'product': ['A', 'B', 'A'],
    'sales': [100, 200, 150]
})
df

         date product  sales
0  2024-01-01       A    100
1  2024-01-02       B    200
2  2024-01-03       A    150

In [72]:

pivot_df = df.pivot(index='date', columns='product', values='sales')
pivot_df
# product      A    B
# date
# 2024-01-01 100  NaN
# 2024-01-02 NaN  200
# 2024-01-03 150  NaN

product         A      B
date
2024-01-01  100.0    NaN
2024-01-02    NaN  200.0
2024-01-03  150.0    NaN

In [74]:
df_duplicate = pd.DataFrame({
    'date': ['2024-01-01', '2024-01-01', '2024-01-02'],
    'product': ['A', 'A', 'B'],
    'sales': [100, 200, 150]
})

pivot_df = df_duplicate.pivot(index='date', columns='product', values='sales')
pivot_df

ValueError: Index contains duplicate entries, cannot reshape

In [75]:
# pivot_table автоматически агрегирует дубли (по умолчанию mean)
pivot_table_df = df_duplicate.pivot_table(
    index='date',
    columns='product',
    values='sales',
    aggfunc='mean'  # можно sum, count, first, и т.д.
)
print(pivot_table_df)
# product        A    B
# date
# 2024-01-01  150.0  NaN
# 2024-01-02  NaN   150.0

product         A      B
date
2024-01-01  150.0    NaN
2024-01-02    NaN  150.0